config/routes.rb
DbcRspecRails::Application.routes.draw do
  namespace :admin do
    resources :posts
  end

  resources :posts

  root :to => "home#index"
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :is_published

  scope :recent, order: "created_at DESC", limit: 5

  before_save :titleize_title

  validates_presence_of :title, :content

  private

  def titleize_title
    self.title = title.titleize
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])

    if @post.save
      flash[:notice] = "Post was successfully saved."
      redirect_to admin_post_url(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(params[:post])
      redirect_to admin_post_url(@post)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:destroy])
    post.destroy

    redirect_to admin_posts_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recent_posts = Post.recent
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post] do |f| %>
  Title:
  <br>
  <%= f.text_field :title %>
  <br>
  <br>

  Content:
  <br>
  <%= f.text_area :content %>
  <br>
  <br>

  Publish? <%= f.check_box :is_published %>
  <br>
  <br>
  <%= f.submit "Save" %>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Edit <%= @post.title %></h1>
<br>
<%= render partial: "form" %>

app/views/admin/posts/index.html.erb
<h1>Welcome to the admin panel!</h1>

<%= link_to "New Post", new_admin_post_url %>

<% if @posts.any? %>
  <h4>All posts:</h4>
  <table>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td>
          <%= link_to "Edit", edit_admin_post_url(post) %>
          <%= link_to "Delete", admin_post_url(post), :method => :delete, :confirm => "Are you sure you want to delete this post?" %>
        </td>
      </tr>
    <% end %>
  </table
<% end %>

app/views/admin/posts/show.html.erb
<% if flash[:notice].present? %>
<p><%= flash[:notice] %></p>
<% end %>
<br>
<%= link_to "Admin welcome page", admin_posts_url %>
<%= link_to "Edit post", edit_admin_post_url(@post) %>
<br>
<br>
Published: <%= @post.is_published? %>
<h1><%= @post.title %></h1>
<%= simple_format @post.content %>

app/views/home/index.html.erb
<H1>Welcome to my blog!</h1>

<%= link_to "View All Posts", posts_url %>

<% if @recent_posts.any? %>
  <h4>Recent Posts:</h4>

  <% @recent_posts.each do |post| %>
    <%= link_to post.title, post_url(post) %>
    <br>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcRspecRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<% if @posts.any? %>
  <% @posts.each do |post| %>
    <h4><%= post.title %></h4>
    <%= simple_format post.content %>
    <hr>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<%= simple_format @post.content %>